name: CI deploy to docker-hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        # YAML syntax for docker/build-push-action, https://github.com/docker/build-push-action/blob/master/README.md.
        uses: docker/build-push-action@v6
        with:
          #platforms: linux/amd64, linux/arm664
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          
